### ISSUE TITLE
downlod not appearing

### ISSUE THREAD

**Issue by shva** [bradlys/monochromatic-panda#6]
i go to any video and it not shows up

chrome-extension://jbfgplhbhmodmikampakabohmkkcdigc/bradlys-ytd-injector.js:161 Couldn't parse script URL for Bradly's YouTube Downloader.
chrome-extension://jbfgplhbhmodmikampakabohmkkcdigc/bradlys-ytd.js Failed to load resource: net::ERR_FILE_NOT_FOUND
https://googleads.g.doubleclick.net/pagead/id Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ytplayer.config.assets.js
"//s.ytimg.com/yts/jsbin/player-iw_IL-vflhQvrpo/base.js"  most importent

**Comment by bradlys** [comment]
Interesting. Do you know what version of the extension you're using? You can just copy and paste this into your URL bar and it'll take you to your extensions. You'll see "Bradly's YouTube Downloader" in bold and then some version number like 0.0.2.5 to the right.

`chrome://extensions/`

If you're using 0.0.2.8 then I'm out of ideas for the moment. As 0.0.2.8 is the most stable release and working release that I have out. I actually haven't published any updates in about 2 months because it has been working so well... I'll circle back to this soon and see if I can figure out what could be the issue.

**Comment by shva** [comment]
thank you very much for your time

it is very interesting i checked out the chrome extensions and it don't
appear your extension

yesterday it did appear
thank you very much
i hope that you can help me

**Comment by shva** [comment]
hi 

i downloaded it again and it works thank you very much for your time

**Comment by shva** [comment]
i cant watch video via proxy can u help?
